### ISSUE TITLE
IE : Homepage View More button top and bottom padding not the same.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Netcab-Express#45]
![image](https://cloud.githubusercontent.com/assets/12791909/10272078/b00b1c0c-6b4c-11e5-9431-be303e32c1eb.png)

**Comment by ermatitan** [comment]
top padding still bigger than the bottom padding. View More text still not vertically centered

**Comment by christiancebudigital** [comment]
please clear cache it is working on our end.

**Comment by ermatitan** [comment]
view more button now displays " Read More
