### ISSUE TITLE
Pre-Footer - Gallery thumbnails should be aligned properly with Gallery title as per psd design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Netcab-Express#72]
![image](https://cloud.githubusercontent.com/assets/12791909/10811666/5c014efa-7e49-11e5-8ad1-5451adf5ebc4.png)

**Comment by christiancebudigital** [comment]
Im confused, "Gallery thumbnails should be not aligned properly with Gallery title as per psd design".
anyways this is now fixed.
